### ISSUE TITLE
Feature request: add a threshold value for the shake event

### ISSUE THREAD

**Issue by jtsimoes** [tpucci/shake_gesture#1]
Hi! Great package here!

Can you add a property inside ShakeGesture() to control the intensity of shake needed to trigger the listener?

Thanks in advance.

**Comment by tpucci** [comment]
Hello there !
Sorry, I have disabled the notifications for Christmas but did not enable them again after 😅
I'll think about a solution this weekend 🙂
Happy to see this package is used by the community

**Comment by tpucci** [comment]
Hey again!
Delivered in 1.1.0 ✅
Check the README: https://github.com/tpucci/shake_gesture#customize-required-shake-gesture

**Comment by dhikshith12** [comment]
Thanks for shipping this feature request 🔥

**Comment by ciriousjoker** [comment]
@tpucci Can you please release v1.1.0? It's not on pub.dev yet.

**Comment by tpucci** [comment]
> @tpucci Can you please release v1.1.0? It's not on pub.dev yet.

Sorry for the misunderstanding. It is available in the 1.1.0 of `shake_gesture_android`.

You can have this feature since the 1.0.3 of `shake_gesture` (currently at 1.0.6).

Check https://pub.dev/packages/shake_gesture/versions

**Comment by ciriousjoker** [comment]
@tpucci ah my bad, got it! I was looking at the docs for the main package and the section for the configuration wasn't added there yet. It might make sense to always update the main package when its platform implementations change, since otherwise you may or may not get any update benefits (or a notification) unless you specify the platform implementation's version in your pubspec, which I doubt many will do.

**Comment by tpucci** [comment]
> @tpucci ah my bad, got it! I was looking at the docs for the main package and the section for the configuration wasn't added there yet. It might make sense to always update the main package when its platform implementations change, since otherwise you may or may not get any update benefits (or a notification) unless you specify the platform implementation's version in your pubspec, which I doubt many will do.

Ahhh right

I should make a symlink between the root README and the main package README. I forgot to update it.

Thanks for pointing that out. Will fix asap.
