### ISSUE TITLE
Bug: `flutter build apk` fails

### ISSUE THREAD

**Issue by lllttt06** [tpucci/shake_gesture#2]
Hi, thank you for providing good a plugin! The problem is I can't build apk by `flutter build apk` command. 
The error message is here.

```
Execution failed for task ':shake_gesture_android:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/tmp/runner/_work/app/app/packages/app/build/shake_gesture_android/intermediates/aapt_friendly_merged_manifests/release/aapt/AndroidManifest.xml:2: AAPT: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'shake_gesture_android'.
```

I can run app by `flutter run` command. Maybe you should change `shake_gesture_android` package name.

**Comment by jtsimoes** [comment]
I'm having this issue too

**Comment by dhikshith12** [comment]
did it work after changing the manifest package name?

**Comment by jtsimoes** [comment]
I couldn't, when I built it, it overwrote what I had changed. Had to use another package

**Comment by tpucci** [comment]
Hello there !
Sorry, I have disabled the notifications for Christmas but did not enable them again after 😅
I'll fix that this weekend 🙂
Happy to see this package is used by the community

**Comment by tpucci** [comment]
Should be fixed in 1.0.1 ✅ You can update this dependency.
Feel free to reopen if there is still an issue 🙂

---

If you want a workaround for the previous version, try this snippet in the root `build.gradle`:

```groovy
// Fixes "Namespace not specified." errors.
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
        }
    }
}
```

**Comment by luke-shields** [comment]
@tpucci This issue exists on the shake_gesture_test_helper just FYI! Thanks so much for developing this :)

**Comment by tpucci** [comment]
Thanks @luke-shields 
Should be fixed in those packages version:

```
Package Name                 
shake_gesture                       1.2.0  
shake_gesture_android               1.1.5
shake_gesture_test_helper           1.1.0
```
