### ISSUE TITLE
The package requires reinstallation of my app

### ISSUE THREAD

**Issue by nausharipov** [tpucci/shake_gesture#5]
I have the following curious case:
1. I have my app installed from TestFlight that uses the "[shake](https://pub.dev/packages/shake)" package
2. I replaced the "shake" package with "shake_gesture" in a new version
3. The "shake_gesture" works well when I test my app locally both on my device and on simulator if I uninstall my app first
4. If I run it locally without uninstalling my app, shaking doesn't work with "shake_gesture"
5. Same with TestFlight: after installing the new version from TestFlight on top of the old one, shaking doesn't work

What might be the reason? How to make the package work without requiring users to uninstall my app first?

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-x64, locale en-KZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Comment by tpucci** [comment]
Very curious indeed 😅

When you say _"Same with TestFlight: after installing the new version from TestFlight on top of the old one, shaking doesn't work"_, you end up having only 1 copy of your app on your phone right ? With the "shake_gesture" package? Shaking does not work in this case?

**Comment by nausharipov** [comment]
Yes, 1 copy, yes, "shake_gesture", yes, doesn't work. I'll prepare a minimal version of this case in the upcoming week.

**Comment by nausharipov** [comment]
I couldn't reproduce the issue with a minimal example app. The reason for my issue is not related to your package. Thank you.
