### ISSUE TITLE
Privacy manifest file for iOS is missing

### ISSUE THREAD

**Issue by Jjagg** [tpucci/shake_gesture#6]
Hi!

Please consider adding a privacy manifest to your library. This helps developers reflect data collection practices in our own manifests. All iOS packages should include a privacy manifest.

[Apple documentation.](https://developer.apple.com/support/third-party-SDK-requirements/)

First-party example: https://github.com/flutter/packages/pull/5846

There's nothing you need to put in there for this package, so you can use an 'empty' manifest:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
	<key>NSPrivacyAccessedAPITypes</key>
	<array/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array/>
	<key>NSPrivacyTracking</key>
	<false/>
</dict>
</plist>
```

**Comment by tpucci** [comment]
Will do ! 👍 Thanks @Jjagg
